#!/usr/bin/env bash

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "${source_dir}"

COLOUR_GREEN='\033[0;32m'
COLOUR_YELLOW='\033[1;33m'
COLOUR_PURPLE='\033[0;35m'
COLOUR_RED='\033[0;31m'
COLOUR_OFF='\033[0;00m'
CLEAR_LINE='\033[2K'

_ERROR_="${COLOUR_RED}[ERROR]${COLOUR_OFF}"
_INFO_="${COLOUR_PURPLE}[INFO]${COLOUR_OFF}"
_DEBUG_="${COLOUR_YELLOW}[DEBUG]${COLOUR_OFF}"

opt_flash=false
opt_debug=false

hyphenjoin() {
  str=""
  while [ $# -gt 0 ]
  do
    str="$str$1-"
    shift
  done
  if [ ! -z "$str" ]
  then
    str="${str::-1}"
  fi
  echo "$str"
}

gccversion() {
  echo "$(arm-none-eabi-gcc -dumpversion)"
}

githash() {
  githash="$(git describe --dirty --always)"
  # Mark as dirty if untracked files exist
  if [ -z "$(echo "$githash" | grep "dirty")" ] && [ ! -z "$(git status --porcelain | grep "^??")" ]; then
    githash="$githash-dirty"
  fi
  echo $githash
}

device_name="STM32F042K6"
device_ram=$((6*1024))
device_flash=$((32*1024))

size_binary() {
  size=`arm-none-eabi-size -A -d $1`;

  size_text=`echo "$size" | grep '\.text' | grep -o -E '[0-9]+' | sed -n 1p`;
  size_rodata=`echo "$size" | grep '\.rodata' | grep -o -E '[0-9]+' | sed -n 1p`;
  size_data=`echo "$size" | grep '\.data' | grep -o -E '[0-9]+' | sed -n 1p`;
  size_bss=`echo "$size" | grep '\.bss' | grep -o -E '[0-9]+' | sed -n 1p`;
  size_heap=`echo "$size" | grep '\.heap' | grep -o -E '[0-9]+' | sed -n 1p`;

  size_flash=$(($size_text+$size_data+$size_rodata));
  size_static=$(($size_data+$size_bss));
  size_ram=$(($size_static+$size_heap));
  size_fdata=$(($size_data+$size_rodata));

  printf "$_INFO_ Device Resources (%s)\n" ${device_name};
  printf "  RAM:       %   6s B / % 6s B\n" ${size_ram} ${device_ram};
  printf "   - Static: %   6s B\n" ${size_static};
  printf "   - Heap:   %   6s B\n" ${size_heap};
  printf "  Flash:     %   6s B / % 6s B (%2s%%)\n" ${size_flash} ${device_flash} $(((100*$size_flash)/$device_flash));
  printf "   - Code:   %   6s B\n" ${size_text};
  printf "   - Data:   %   6s B\n" ${size_fdata};
}

## Read Flags
OPTIND=1
while getopts ":DF" opt; do
  case "$opt" in
    D) # Debug
      opt_debug=true
      ;;
    F) # Flash
      opt_flash=true
      ;;
    ?) # Illegal Option
      echo -e "$_ERROR_ Illegal option '$OPTARG'"
      exit 3
      ;;
  esac
done
for i in `seq 2 $OPTIND`; do shift; done

githash_var=`githash`
filename="$(hyphenjoin "resolver" "${githash_var}")"

flags="TARGET_FILENAME=\"${filename}\" GITVERSION=\"${githash_var}\""

printf "$_INFO_ Using GCC version: `gccversion`\n";
printf "$_INFO_ Firmware version: ${githash_var}\n";
printf "$_INFO_ Compiling..\n";
make ${flags} \
&& {
  printf "$_INFO_$COLOUR_GREEN Compile OK$COLOUR_OFF\n"
  size_binary "builds/${filename}.elf"
  if $opt_debug;
  then
    ./debug "builds/${filename}";
  elif $opt_flash;
  then
    ./flash "builds/${filename}";
  fi
}
